### ISSUE TITLE
Why is the default for "mousemove" not cancelable?

### ISSUE THREAD

**Issue by blink1073** [blakeembrey/simulate-event#16]
@blakeembrey, you had made this change in #9 and it just bit me on some unit tests I was writing.

**Comment by blakeembrey** [comment]
Pretty sure it's been around for longer than that. That PR was only stylistic changes.

**Comment by blakeembrey** [comment]
Yeah, my first commit two years ago used it: https://github.com/blakeembrey/simulate-event/commit/39a228a0e0cd59f06af0c5abfdf25f0922bef68e#diff-5c95ee1fc042ea7afc23150279f17cb8R109

**Comment by blink1073** [comment]
Ah, `git blame` fooled me ;).

**Comment by blink1073** [comment]
Are you against making it consistent with the other mouse events?

**Comment by blakeembrey** [comment]
Nope, not at all. Go ahead 👍 It's yours to improve now. I'll quickly try and remember why I did that, but I honestly can't tell you right now.

**Comment by blink1073** [comment]
It looks like `mouseenter` and `mouseleave` are not cancelable, but I don't see a reason to do it for `mousemove`: https://www.w3.org/TR/DOM-Level-3-Events/#event-type-mousemove

**Comment by blink1073** [comment]
Perhaps it was because of this?  "Note: This event was formerly specified to be non-cancelable in DOM Level 2 Events [DOM2 Events], but was changed to reflect existing interoperability between user agents."

**Comment by blakeembrey** [comment]
Wow, that's odd - the level 2 spec says it's not cancellable: https://www.w3.org/TR/DOM-Level-2-Events/events.html

**Comment by blakeembrey** [comment]
Cool, yep 👍 Let's definitely fix it then 😄

**Comment by blink1073** [comment]
Ha!  DOM specs are fun ;).

**Comment by blink1073** [comment]
Okay, PR coming.

**Comment by blakeembrey** [comment]
Cool. It's probably I did it at the time because of older browser support and making it act consistent across browser. Honestly though, it seems reasonable to support it.
