### ISSUE TITLE
Switch to new DOM APIs?

### ISSUE THREAD

**Issue by blink1073** [blakeembrey/simulate-event#6]
The usage of the `init*()` functions is deprecated, and instead the options are meant to be passed to the constructor.  As it stands, keyboard events are not being created properly when using Firefox.  Would you accept a PR that makes this change?  

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/initKeyboardEvent

**Comment by blakeembrey** [comment]
I will absolutely accept any PRs improving the functionality. As I'm not doing a great job maintaining this myself anymore, if you'd like to take over the package and improve it you're welcome to 😄 Just let me know and I can add you as a collaborator after the PR.

**Comment by markrian** [comment]
When I first contributed to this project I wanted to add support for the standard event construction APIs, but I never got around to it. I'm evidently not doing a great job as a collaborator!

A PR would be great - perhaps where standard APIs are preferred, but deprecated APIs are used as fallbacks.

**Comment by blink1073** [comment]
Yes, I have since realized that IE11 does not support the new constructors like `new KeyboardEvent()`.
