### ISSUE TITLE
Support creating an event without dispatching

### ISSUE THREAD

**Issue by blink1073** [blakeembrey/simulate-event#8]
The use case is for creating custom events derived from native events, or saving a cloned event for later.
This could be accomplished by passing `void 0` as the target element, adding another argument, or by creating a separate function.

**Comment by blakeembrey** [comment]
Sounds great, I'd add a new function and use that in the existing function, by the sounds of it.

**Comment by blink1073** [comment]
Fixed by #10.

**Comment by blakeembrey** [comment]
@blink1073 What was your NPM username? I can add you to publish too. Just make sure you do `npm version` to have the commit/tag and add some simple release notes 😄 The next release should be 1.0, I believe.

**Comment by blink1073** [comment]
It is also `blink1073` (my AOL moniker ~1999).

**Comment by blakeembrey** [comment]
Done. All yours 😄 (https://www.npmjs.com/package/simulate-event)

**Comment by blink1073** [comment]
`simulate-event@1.0.0` published, cheers.
